USE [master]
GO
/****** Object:  Database [QLBanDienThoai]    Script Date: 24/04/2026 15:31:26 ******/
CREATE DATABASE [QLBanDienThoai]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'QLBanDienThoai', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL16.SQLEXPRESS01\MSSQL\DATA\QLBanDienThoai.mdf' , SIZE = 73728KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB )
 LOG ON 
( NAME = N'QLBanDienThoai', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL16.SQLEXPRESS01\MSSQL\DATA\QLBanDienThoai_log.ldf' , SIZE = 8192KB , MAXSIZE = 2048GB , FILEGROWTH = 65536KB )
 WITH CATALOG_COLLATION = DATABASE_DEFAULT, LEDGER = OFF
GO
ALTER DATABASE [QLBanDienThoai] SET COMPATIBILITY_LEVEL = 160
GO
IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [QLBanDienThoai].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO
ALTER DATABASE [QLBanDienThoai] SET ANSI_NULL_DEFAULT OFF 
GO
ALTER DATABASE [QLBanDienThoai] SET ANSI_NULLS OFF 
GO
ALTER DATABASE [QLBanDienThoai] SET ANSI_PADDING OFF 
GO
ALTER DATABASE [QLBanDienThoai] SET ANSI_WARNINGS OFF 
GO
ALTER DATABASE [QLBanDienThoai] SET ARITHABORT OFF 
GO
ALTER DATABASE [QLBanDienThoai] SET AUTO_CLOSE OFF 
GO
ALTER DATABASE [QLBanDienThoai] SET AUTO_SHRINK OFF 
GO
ALTER DATABASE [QLBanDienThoai] SET AUTO_UPDATE_STATISTICS ON 
GO
ALTER DATABASE [QLBanDienThoai] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO
ALTER DATABASE [QLBanDienThoai] SET CURSOR_DEFAULT GLOBAL 
GO
ALTER DATABASE [QLBanDienThoai] SET CONCAT_NULL_YIELDS_NULL OFF 
GO
ALTER DATABASE [QLBanDienThoai] SET NUMERIC_ROUNDABORT OFF 
GO
ALTER DATABASE [QLBanDienThoai] SET QUOTED_IDENTIFIER OFF 
GO
ALTER DATABASE [QLBanDienThoai] SET RECURSIVE_TRIGGERS OFF 
GO
ALTER DATABASE [QLBanDienThoai] SET ENABLE_BROKER 
GO
ALTER DATABASE [QLBanDienThoai] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO
ALTER DATABASE [QLBanDienThoai] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO
ALTER DATABASE [QLBanDienThoai] SET TRUSTWORTHY OFF 
GO
ALTER DATABASE [QLBanDienThoai] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO
ALTER DATABASE [QLBanDienThoai] SET PARAMETERIZATION SIMPLE 
GO
ALTER DATABASE [QLBanDienThoai] SET READ_COMMITTED_SNAPSHOT OFF 
GO
ALTER DATABASE [QLBanDienThoai] SET HONOR_BROKER_PRIORITY OFF 
GO
ALTER DATABASE [QLBanDienThoai] SET RECOVERY FULL 
GO
ALTER DATABASE [QLBanDienThoai] SET MULTI_USER 
GO
ALTER DATABASE [QLBanDienThoai] SET PAGE_VERIFY CHECKSUM 
GO
ALTER DATABASE [QLBanDienThoai] SET DB_CHAINING OFF 
GO
ALTER DATABASE [QLBanDienThoai] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO
ALTER DATABASE [QLBanDienThoai] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO
ALTER DATABASE [QLBanDienThoai] SET DELAYED_DURABILITY = DISABLED 
GO
ALTER DATABASE [QLBanDienThoai] SET ACCELERATED_DATABASE_RECOVERY = OFF 
GO
EXEC sys.sp_db_vardecimal_storage_format N'QLBanDienThoai', N'ON'
GO
ALTER DATABASE [QLBanDienThoai] SET QUERY_STORE = ON
GO
ALTER DATABASE [QLBanDienThoai] SET QUERY_STORE (OPERATION_MODE = READ_WRITE, CLEANUP_POLICY = (STALE_QUERY_THRESHOLD_DAYS = 30), DATA_FLUSH_INTERVAL_SECONDS = 900, INTERVAL_LENGTH_MINUTES = 60, MAX_STORAGE_SIZE_MB = 1000, QUERY_CAPTURE_MODE = AUTO, SIZE_BASED_CLEANUP_MODE = AUTO, MAX_PLANS_PER_QUERY = 200, WAIT_STATS_CAPTURE_MODE = ON)
GO
USE [QLBanDienThoai]
GO

/******Object: table SanPham*******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[SanPham](
	[ID] [int] IDENTITY(1,1) NOT NULL,
	[TenSP] [nvarchar](255) NOT NULL,
	[ThuongHieu] [nvarchar](255) NULL,
	[Xuatxu] [nvarchar](50) NULL,
	[MaLoai] [int] NULL,
	[GiaBan] [decimal](18, 2) NULL,
	[SoLuong] [int] NULL,
	[HinhAnh] [nvarchar](255) NULL,
	[MoTa] [nvarchar](max) NULL,
	[maNCC] [int] NULL,
	[TrangThai] [bit] NULL,
	[MaSP]  AS ('SP'+right('000'+CONVERT([varchar](3),[ID]),(3))) PERSISTED,
PRIMARY KEY CLUSTERED 
(
	[ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]
GO

/******Object: table CTSanPham*******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[CTSanPham](
	[MaCTSP] [int] IDENTITY(1,1) NOT NULL,
	[ID] [int] NOT NULL,
	[ChatLieuVo] [nvarchar](50) NULL,
	[ChatLieuDay] [nvarchar](50) NULL,
	[BaoHanh] [nvarchar](100) NULL,
	[TrongLuong] [decimal](6, 2) NULL,
 CONSTRAINT [PK__CTSanPha__1E4FCECD7161CA13] PRIMARY KEY CLUSTERED 
(
	[MaCTSP] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
